BASE_LOCATION_ID = 0xD15500000
LOCATION_MAPPING = {
    -- Between areas
    [BASE_LOCATION_ID + 0x2F] = { { "@Connecting Portals/Room A And Treasury B/Lucky Charm" } },
    [BASE_LOCATION_ID + 0x88] = { { "@Connecting Portals/Luminous B and Walkway A/Steel Glove" } },

	-- Entrance A
	[BASE_LOCATION_ID + 0xB2] = { { "@Entrance A/Gatehouse Tower Top/Big Mana Prism" } },
	[BASE_LOCATION_ID + 0x2E] = { { "@Entrance A/Gatehouse Tower Break Room/Magic Armor" } },
	[BASE_LOCATION_ID + 0xB5] = { { "@Entrance A/Sea Chicken Chamber Upper/Potion" } },
	[BASE_LOCATION_ID + 0xB6] = { { "@Entrance A/Sea Chicken Chamber Lower/Potion" } },
	[BASE_LOCATION_ID + 0x64] = { { "@Entrance A/Upper Guard Hall/Heart Max Up" } },
	[BASE_LOCATION_ID + 0x2B] = { { "@Entrance A/Warp Winery/Platinum Whip" } },
	[BASE_LOCATION_ID + 0xAC] = { { "@Entrance A/Hangman's Hall/Leather Boots" } },
	[BASE_LOCATION_ID + 0x0F] = { { "@Entrance A/Hangman's Balcony/Soul Orb" } },
	[BASE_LOCATION_ID + 0x46] = { { "@Entrance A/Subterranean Shaft Top/Life Max Up" } },
	[BASE_LOCATION_ID + 0x08] = { { "@Entrance A/Subterranean Warp Room/Hint Card 3" } },
	[BASE_LOCATION_ID + 0x3C] = { { "@Entrance A/Upper Floor Warp Room/Hint Card 3" } },
	[BASE_LOCATION_ID + 0x82] = { { "@Entrance A/Triple Skull Table/Leather Armor" } },

    -- Entrance B
    [BASE_LOCATION_ID + 0xA2] = { { "@Entrance B/Start Of The Other's Adventure/War Fatigues" } },
    [BASE_LOCATION_ID + 0xE0] = { { "@Entrance B/Observation Tower Top/Ancient Urn" } },
    [BASE_LOCATION_ID + 0xE1] = { { "@Entrance B/Observation Tower Top/Big Mana Prism" } },
    [BASE_LOCATION_ID + 0x14] = { { "@Entrance B/Observation Tower Atlas Chamber/Rib of Vlad" } },
    [BASE_LOCATION_ID + 0x0A] = { { "@Entrance B/Warped Wine Cellar/Lure Key" } },
    [BASE_LOCATION_ID + 0x77] = { { "@Entrance B/Double Hangman's Patio/Heart Max Up" } },
    [BASE_LOCATION_ID + 0xE3] = { { "@Entrance B/Secret Skeletal Passage Middle/Top (Pretty Vase)" } },
    [BASE_LOCATION_ID + 0xE4] = { { "@Entrance B/Secret Skeletal Passage Middle/Bottom (High Potion)" } },
    [BASE_LOCATION_ID + 0xE7] = { { "@Entrance B/Secret Skeletal Passage Lower/Big Mana Prism" } },

	-- Marble Corridor A
	[BASE_LOCATION_ID + 0x65] = { { "@Marble Corridor A/Push Crate Storage/Left (Heart Max Up)" } },
	[BASE_LOCATION_ID + 0x19] = { { "@Marble Corridor A/Push Crate Storage/Right (Ice Book)" } },
	[BASE_LOCATION_ID + 0x23] = { { "@Marble Corridor A/West Common Room/Castle Map 1" } },
	[BASE_LOCATION_ID + 0xA7] = { { "@Marble Corridor A/Above Giant Bat Hall/Leather Glove" } },
	[BASE_LOCATION_ID + 0x18] = { { "@Marble Corridor A/Save Slide Storage/Left (Fire Book)" } },
	[BASE_LOCATION_ID + 0x9C] = { { "@Marble Corridor A/Save Slide Storage/Right (Summer Clothes)" } },
	[BASE_LOCATION_ID + 0x26] = { { "@Marble Corridor A/East Common Room/Red Stone" } },
	[BASE_LOCATION_ID + 0xB7] = { { "@Marble Corridor A/Grand Staircase Window Ledge/Anti-venom" } },
	[BASE_LOCATION_ID + 0x67] = { { "@Marble Corridor A/Grand Staircase Above Window Ledge/Heart Max Up" } },
	[BASE_LOCATION_ID + 0xB9] = { { "@Marble Corridor A/Grand Staircase Bottom Bunker/Left (Potion)" } },
	[BASE_LOCATION_ID + 0xB8] = { { "@Marble Corridor A/Grand Staircase Bottom Bunker/Right (Anti-venom)" } },
	[BASE_LOCATION_ID + 0x17] = { { "@Marble Corridor A/Grand Staircase Top Storage/Upper (Vlad's Ring)" } },
	[BASE_LOCATION_ID + 0x66] = { { "@Marble Corridor A/Grand Staircase Top Storage/Lower (Heart Max Up)" } },
	[BASE_LOCATION_ID + 0x48] = { { "@Marble Corridor A/Hope of Victory Hall/Life Max Up" } },
	[BASE_LOCATION_ID + 0x10] = { { "@Marble Corridor A/Wailing Exit/Fairy Journal" } },
	[BASE_LOCATION_ID + 0xBB] = { { "@Marble Corridor A/Descent of Illusion/Potion" } },

    -- Marble Corridor B
    [BASE_LOCATION_ID + 0x59] = { { "@Marble Corridor B/Lizard Family Reunion/Life Max Up" } },
    [BASE_LOCATION_ID + 0xA6] = { { "@Marble Corridor B/Save Secret Crawlspace/Twilight Cloak" } },
    [BASE_LOCATION_ID + 0xEB] = { { "@Marble Corridor B/East Uncommon Room/High Potion" } },
    [BASE_LOCATION_ID + 0x9B] = { { "@Marble Corridor B/Flea Man Armory/Viking Helmet" } },
    [BASE_LOCATION_ID + 0x78] = { { "@Marble Corridor B/0 Hope of Victory Hall/Heart Max Up" } },
	
	-- Room of Illusion A
    [BASE_LOCATION_ID + 0x90] = { { "@Room Of Illusion A/Lava Flow Chamber/Fancy Bandana" } },
    [BASE_LOCATION_ID + 0x47] = { { "@Room Of Illusion A/Lizard-man Turf/Life Max Up" } },
    [BASE_LOCATION_ID + 0x68] = { { "@Room Of Illusion A/Crawlspace To The Other World/Heart Max Up" } },

    -- Room of Illusion B
    [BASE_LOCATION_ID + 0xED] = { { "@Room Of Illusion B/Battlegrounds Of Many Victories/Silk Curtain" } },
    [BASE_LOCATION_ID + 0x5B] = { { "@Room Of Illusion B/Spriggan Into Action/Heart Max Up" } },

	-- The Wailing Way A
	[BASE_LOCATION_ID + 0xA3] = { { "@The Wailing Way A/Ghostly Graveyard Left Ground Tomb/Silk Cloak" } },
    [BASE_LOCATION_ID + 0x11] = { { "@The Wailing Way A/Ghostly Graveyard Ghostly Graveyard Pedestal/Monster Tome" } },
    [BASE_LOCATION_ID + 0x49] = { { "@The Wailing Way A/Ghostly Graveyard Ghostly Ceiling Tomb/Life Max Up" } },
    [BASE_LOCATION_ID + 0xBC] = { { "@The Wailing Way A/Ghostly Graveyard Right Ground Tomb/Drumstick" } },
    [BASE_LOCATION_ID + 0xBA] = { { "@The Wailing Way A/Gryffin Crossroads Ceiling Tomb/Mana Prism" } },
    [BASE_LOCATION_ID + 0x83] = { { "@The Wailing Way A/West Of Crossroads Ceiling Tomb/Potion" } },
    [BASE_LOCATION_ID + 0x30] = { { "@The Wailing Way A/U-Bendy Passages - Left/Logoth's Ring" } },
    [BASE_LOCATION_ID + 0x9D] = { { "@The Wailing Way A/U-Bendy Passages - Right/Fancy Clothes" } },
    [BASE_LOCATION_ID + 0x69] = { { "@The Wailing Way A/Lone Lizard Skull Door/Heart Max Up" } },

    -- The Wailing Way B
    [BASE_LOCATION_ID + 0x5A] = { { "@The Wailing Way B/Deserted Cemetary Pedestal/Life Max Up" } },
    [BASE_LOCATION_ID + 0xEE] = { { "@The Wailing Way B/Deserted Cemetary Top Alcove/Anti-venom" } },
    [BASE_LOCATION_ID + 0xF0] = { { "@The Wailing Way B/Silent Stairs Top Balcony/Candleholder" } },
    [BASE_LOCATION_ID + 0x04] = { { "@The Wailing Way B/Contorted Pants Room - Top-Left/Crush Boots" } },
    [BASE_LOCATION_ID + 0xF2] = { { "@The Wailing Way B/Contorted Pants Room - Top-Right/Smiling Statue" } },
    [BASE_LOCATION_ID + 0xF3] = { { "@The Wailing Way B/Contorted Pants Room - Bottom-Right/Potion" } },

	-- Shrine Of The Apostates A
	[BASE_LOCATION_ID + 0xBE] = { { "@Shrine of the Apostates A/Lizard Land Storerooms - Left/Drumstick" } },
    [BASE_LOCATION_ID + 0xBF] = { { "@Shrine of the Apostates A/Lizard Land Storerooms - Right/Opal" } },
    [BASE_LOCATION_ID + 0x2C] = { { "@Shrine of the Apostates A/Dead Victory Casket/Energy Circle" } },
    [BASE_LOCATION_ID + 0xBD] = { { "@Shrine of the Apostates A/Wailing Exit/Potion" } },
    [BASE_LOCATION_ID + 0x4A] = { { "@Shrine of the Apostates A/White Dragon's Treasure/Life Max Up" } },
    [BASE_LOCATION_ID + 0x01] = { { "@Shrine of the Apostates A/Behind Living Armor/Lizard Tail" } },
    [BASE_LOCATION_ID + 0x4B] = { { "@Shrine of the Apostates A/Lower Lizard Crawlspace/Life Max Up" } },

    -- Shrine of the Apostates B
    [BASE_LOCATION_ID + 0xF5] = { { "@Shrine of the Apostates B/Bouncing Bone Zone Above Coffin/Turkey" } },
    [BASE_LOCATION_ID + 0x7A] = { { "@Shrine of the Apostates B/Bouncing Bone Zone Coffin/Heart Max Up" } },
    [BASE_LOCATION_ID + 0xF6] = { { "@Shrine of the Apostates B/Simon Says Square/Drumstick" } },
    [BASE_LOCATION_ID + 0xF7] = { { "@Shrine of the Apostates B/Left Owl House/Elixir" } },
    [BASE_LOCATION_ID + 0x79] = { { "@Shrine of the Apostates B/Before Cyclops/Heart Max Up" } },

	-- Castle Treasury A
    [BASE_LOCATION_ID + 0xCB] = { { "@Castle Treasury A/West Spectral Hangout/Left (Teacup)" } },
    [BASE_LOCATION_ID + 0xCC] = { { "@Castle Treasury A/West Spectral Hangout/Right (Teapot)" } },
    [BASE_LOCATION_ID + 0x52] = { { "@Castle Treasury A/West Chapel Save Room Dead End/Life Max Up" } },
    [BASE_LOCATION_ID + 0x3D] = { { "@Castle Treasury A/West Chapel Warp Room/Hint Card 3" } },
    [BASE_LOCATION_ID + 0x34] = { { "@Castle Treasury A/Hall Of The Ruler/Greed Amulet" } },
    [BASE_LOCATION_ID + 0xCD] = { { "@Castle Treasury A/Stairs Of The Ruler/Potion" } },
    [BASE_LOCATION_ID + 0xCE] = { { "@Castle Treasury A/Prase Quartz Mine Upper Tunnel/Closet" } },
    [BASE_LOCATION_ID + 0x8C] = { { "@Castle Treasury A/Merchant's Open Hideout/Plate Mail" } },
    [BASE_LOCATION_ID + 0x71] = { { "@Castle Treasury A/Prase Quartz Mine Lower Tunnel/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x32] = { { "@Castle Treasury A/Prase Quartz Mine Top Chamber/Heaven's Ring" } },
    [BASE_LOCATION_ID + 0x31] = { { "@Castle Treasury A/Above Elevator Guarded Stairs/Holy Ring" } },
    [BASE_LOCATION_ID + 0xCF] = { { "@Castle Treasury A/Entrance To Center/Chandelier" } },
    [BASE_LOCATION_ID + 0x85] = { { "@Castle Treasury A/Moonlit Elevator Warp Room/Right (Platinum Shoes)" } },
    [BASE_LOCATION_ID + 0x33] = { { "@Castle Treasury A/Moonlit Elevator Warp Room/Left (Moon Armor)" } },

    -- Castle Treasury B
    [BASE_LOCATION_ID + 0x1F] = { { "@Castle Treasury B/West Volcano Shelter - Left/Wristband" } },
    [BASE_LOCATION_ID + 0x102] = { { "@Castle Treasury B/West Volcano Shelter - Right/Uncurse Potion" } },
    [BASE_LOCATION_ID + 0x7B] = { { "@Castle Treasury B/West Volcanic Save Room/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x5D] = { { "@Castle Treasury B/West Volcanic Lure Hall/Life Max Up" } },
    [BASE_LOCATION_ID + 0x24] = { { "@Castle Treasury B/Portal Staircase Bottom/Potion" } },
    [BASE_LOCATION_ID + 0x103] = { { "@Castle Treasury B/Rose Quartz Mine Lower Tunnel/Chair" } },
    [BASE_LOCATION_ID + 0x84] = { { "@Castle Treasury B/Rose Quartz Mine Top Chamber/Cloth Tunic" } },
    [BASE_LOCATION_ID + 0x86] = { { "@Castle Treasury B/Above Elevator Unguarded Stairs - Left/Padded Armor" } },
    [BASE_LOCATION_ID + 0x7C] = { { "@Castle Treasury B/Above Elevator Unguarded Stairs - Right/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x42] = { { "@Castle Treasury B/Sunny Elevator Warp Room/Sun Armor" } },

    -- Skeleton Cave A
	[BASE_LOCATION_ID + 0xA1] = { { "@Skeleton Cave A/Medusa's Remains Chamber - Left/Lightning Robes" } },
    [BASE_LOCATION_ID + 0xC8] = { { "@Skeleton Cave A/Medusa's Remains Chamber - Right/Phonograph" } },
    [BASE_LOCATION_ID + 0xC9] = { { "@Skeleton Cave A/Monument To The Evil God/Bookshelf" } },
    [BASE_LOCATION_ID + 0x72] = { { "@Skeleton Cave A/Far-Right Push Crate Challenge/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x54] = { { "@Skeleton Cave A/Outside Skeleton Testing Chamber/Life Max Up" } },
    [BASE_LOCATION_ID + 0x36] = { { "@Skeleton Cave A/Behind Legion (Corpse)/Cipher's Charm" } },
    [BASE_LOCATION_ID + 0x35] = { { "@Skeleton Cave A/Museum Of Mimics End Room/Rare Ring" } },
    [BASE_LOCATION_ID + 0xCA] = { { "@Skeleton Cave A/Secret Attic Above Save Room/Left (Big Mana Prism)" } },
    [BASE_LOCATION_ID + 0x53] = { { "@Skeleton Cave A/Secret Attic Above Save Room/Right (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x02] = { { "@Skeleton Cave A/Crate Balancing Act Chamber/Floodgate Key" } },
    [BASE_LOCATION_ID + 0x21] = { { "@Skeleton Cave A/Museum Of Mimics Above End Room/Hint Card 5" } },

    -- Skeleton Cave B
    [BASE_LOCATION_ID + 0xFC] = { { "@Skeleton Cave B/Giant Ghost's Remains Chamber - Lower/Potion" } },
    [BASE_LOCATION_ID + 0xAD] = { { "@Skeleton Cave B/Giant Ghost's Remains Chamber - Upper/Ankle Guards" } },
    [BASE_LOCATION_ID + 0x7D] = { { "@Skeleton Cave B/Monument To Carmilla/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x2D] = { { "@Skeleton Cave B/Lower Spider Den Wall/Bullet Tip" } },
    [BASE_LOCATION_ID + 0xFD] = { { "@Skeleton Cave B/Rolling Skull Chamber/Side Table" } },
    [BASE_LOCATION_ID + 0xFE] = { { "@Skeleton Cave B/Crocomire Graveyard/Stuffed Stag" } },
    [BASE_LOCATION_ID + 0x06] = { { "@Skeleton Cave B/Behind Skull Knight/Sylph's Feather" } },
    [BASE_LOCATION_ID + 0x5E] = { { "@Skeleton Cave B/Museum Of Skulls/Life Max Up" } },
    [BASE_LOCATION_ID + 0x1C] = { { "@Skeleton Cave B/Secret Attic Above Save Room/Left (Summoning Tome)" } },
    [BASE_LOCATION_ID + 0xFF] = { { "@Skeleton Cave B/Secret Attic Above Save Room/Right (Wizard's Urn)" } },
    [BASE_LOCATION_ID + 0x92] = { { "@Skeleton Cave B/Castle Entrance Ascent Point/Leather Cap" } },

    -- Luminous Cavern A
    [BASE_LOCATION_ID + 0xD0] = { { "@Luminous Cavern A/Near Aqueduct Exit/Drumstick" } },
    [BASE_LOCATION_ID + 0x76] = { { "@Luminous Cavern A/Outside Destructible Wall Warp - Left/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x99] = { { "@Luminous Cavern A/Outside Destructible Wall Warp - Right/Full Helmet" } },
    [BASE_LOCATION_ID + 0x6B] = { { "@Luminous Cavern A/Beneath Hammer-Hammer's Home Shaft/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x58] = { { "@Luminous Cavern A/Behind Talos/Left (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x6C] = { { "@Luminous Cavern A/Behind Talos/Right (Heart Max Up)" } },
    [BASE_LOCATION_ID + 0x09] = { { "@Luminous Cavern A/Hammer-Hammer's Home/Skull Key" } },
    [BASE_LOCATION_ID + 0x3E] = { { "@Luminous Cavern A/Destructible Wall Warp Room/Platinum Crown" } },
    [BASE_LOCATION_ID + 0x1D] = { { "@Luminous Cavern A/Path To Floodgate/Hint Card 1" } },
    [BASE_LOCATION_ID + 0xAB] = { { "@Luminous Cavern A/Death's Flooded Upper Cavern/Arm Plates" } },
    [BASE_LOCATION_ID + 0xB0] = { { "@Luminous Cavern A/Death's Flooded Lower Cavern/Leggings" } },
    [BASE_LOCATION_ID + 0xD2] = { { "@Luminous Cavern A/Dead End Chamber Above Talos/Medicine Jar" } },
    [BASE_LOCATION_ID + 0x03] = { { "@Luminous Cavern A/Behind Death/Griffin's Wing" } },
    
    -- Luminous Cavern B
    [BASE_LOCATION_ID + 0x104] = { { "@Luminous Cavern B/Near Aqueduct Exit/Turquoise" } },
    [BASE_LOCATION_ID + 0x10B] = { { "@Luminous Cavern B/Outside Indestructible Wall Warp - Left/Mana Prism" } },
    [BASE_LOCATION_ID + 0x10C] = { { "@Luminous Cavern B/Outside Indestructible Wall Warp - Right/Sage Statue" } },
    [BASE_LOCATION_ID + 0x44] = { { "@Luminous Cavern B/Execution Elevator Shaft - Upper/Walk Armor" } },
    [BASE_LOCATION_ID + 0x10D] = { { "@Luminous Cavern B/Execution Elevator Shaft - Lower/Elixir" } },
    [BASE_LOCATION_ID + 0x28] = { { "@Luminous Cavern B/Execution Elevator Slimy Storage/Left (Yellow Stone)" } },
    [BASE_LOCATION_ID + 0x10F] = { { "@Luminous Cavern B/Execution Elevator Slimy Storage/Right (Strange Mirror)" } },
    [BASE_LOCATION_ID + 0x10E] = { { "@Luminous Cavern B/Path To Push Crates/Silver Dishes" } },
    [BASE_LOCATION_ID + 0x63] = { { "@Luminous Cavern B/Push Crate Puzzle Reward/Life Max Up" } },
    [BASE_LOCATION_ID + 0x81] = { { "@Luminous Cavern B/Path to Sky Portal Upper Cavern/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x110] = { { "@Luminous Cavern B/Path to Sky Portal Lower Cavern/High Potion" } },
    [BASE_LOCATION_ID + 0x111] = { { "@Luminous Cavern B/Dead End Chamber Above Golem - Left/Potion" } },
    [BASE_LOCATION_ID + 0x112] = { { "@Luminous Cavern B/Dead End Chamber Above Golem - Right/Uncurse Potion" } },

    -- Sky Walkway A
    [BASE_LOCATION_ID + 0x07] = { { "@Sky Walkway A/Maxim's Memento/MK Bracelet" } },
    [BASE_LOCATION_ID + 0xD6] = { { "@Sky Walkway A/Under Construction Chamber - Upper/Anti-venom" } },
    [BASE_LOCATION_ID + 0xD7] = { { "@Sky Walkway A/Under Construction Chamber - Middle/High Potion" } },
    [BASE_LOCATION_ID + 0x56] = { { "@Sky Walkway A/Under Construction Chamber - Lower/Life Max Up" } },
    [BASE_LOCATION_ID + 0xD9] = { { "@Sky Walkway A/Above Devil Right Tower/Silver Trinket" } },
    [BASE_LOCATION_ID + 0xDA] = { { "@Sky Walkway A/Above Devil Left Tower/Gold Trinket" } },
    [BASE_LOCATION_ID + 0xDB] = { { "@Sky Walkway A/Above Devil White Dragon/Elixir" } },
    [BASE_LOCATION_ID + 0x3A] = { { "@Sky Walkway A/After Devil/Night Goggles" } },
    [BASE_LOCATION_ID + 0xDC] = { { "@Sky Walkway A/Save Room Wall Hot Spring/Left (Medicine Jar)" } },
    [BASE_LOCATION_ID + 0xDD] = { { "@Sky Walkway A/Save Room Wall Hot Spring/Right (Medicine Jar)" } },
    [BASE_LOCATION_ID + 0x94] = { { "@Sky Walkway A/Upper Dark Hallway/Face-guard" } },
    [BASE_LOCATION_ID + 0x3B] = { { "@Sky Walkway A/Lower Dark Hallway - Left Crawlspace/Chaos Ring" } },
    [BASE_LOCATION_ID + 0x1E] = { { "@Sky Walkway A/Lower Dark Hallway - Right Crawlspace/Hint Card 2" } },

    -- Sky Walkway B
    [BASE_LOCATION_ID + 0x60] = { { "@Sky Walkway B/Before Shadow/Life Max Up" } },
    [BASE_LOCATION_ID + 0x9F] = { { "@Sky Walkway B/Over Construction Chamber - Middle/Blizzard Robe" } },
    [BASE_LOCATION_ID + 0x118] = { { "@Sky Walkway B/Over Construction Chamber - Bottom-Left/Old Radio" } },
    [BASE_LOCATION_ID + 0x119] = { { "@Sky Walkway B/Over Construction Chamber - Bottom-Right/Rocking Chair" } },
    [BASE_LOCATION_ID + 0x80] = { { "@Sky Walkway B/Above Legion (Saint) Left Tower/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x11A] = { { "@Sky Walkway B/Above Legion (Saint) Right Tower/King-Size Bed" } },
    [BASE_LOCATION_ID + 0x8A] = { { "@Sky Walkway B/Before Legion (Saint)/Mana Prism" } },
    [BASE_LOCATION_ID + 0x13] = { { "@Sky Walkway B/Save Room Wall Dried Spring/Heart of Vlad" } },
    [BASE_LOCATION_ID + 0x11B] = { { "@Sky Walkway B/Hall Of Mirrors Entrance/Turkey" } },
    [BASE_LOCATION_ID + 0x7F] = { { "@Sky Walkway B/Museum Of Murder/Heart Max Up" } },

    -- Chapel of Dissonance A
    [BASE_LOCATION_ID + 0x4D] = { { "@Chapel of Dissonance A/Main Building Highest Tower - Left/Life Max Up" } },
    [BASE_LOCATION_ID + 0xD3] = { { "@Chapel of Dissonance A/Main Building Highest Tower - Right/Potion" } },
    [BASE_LOCATION_ID + 0xA4] = { { "@Chapel of Dissonance A/Main Building Central Stairs Ledge/Emerald Cloak" } },
    [BASE_LOCATION_ID + 0x12] = { { "@Chapel of Dissonance A/Main Building Middle Tower/Eye of Vlad" } },
    [BASE_LOCATION_ID + 0x6A] = { { "@Chapel of Dissonance A/Main Building Lowest Tower/Heart Max Up" } },
    [BASE_LOCATION_ID + 0xD5] = { { "@Chapel of Dissonance A/Walkway Passage/Anti-venom" } },

    -- Chapel of Dissonance B
    [BASE_LOCATION_ID + 0x115] = { { "@Chapel of Dissonance B/Main Building Tallest Tower/Big Mana Prism" } },
    [BASE_LOCATION_ID + 0x6F] = { { "@Chapel of Dissonance B/Main Building Middle Stairs Ledge/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x4F] = { { "@Chapel of Dissonance B/Main Building Center Tower/Upper (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x22] = { { "@Chapel of Dissonance B/Main Building Center Tower/Lower (Hint Card 6)" } },
    [BASE_LOCATION_ID + 0x116] = { { "@Chapel of Dissonance B/Main Building Lowest Tower/Hero Statue" } },
    [BASE_LOCATION_ID + 0x117] = { { "@Chapel of Dissonance B/Corridors Of Frightening Lightning/High Potion" } },

    -- Clock Tower A
    [BASE_LOCATION_ID + 0x95] = { { "@Clock Tower A/West Entrance Shaft Bottom/Bagonette" } },
    [BASE_LOCATION_ID + 0x20] = { { "@Clock Tower A/Medusa's Home Attic/Hint Card 4" } },
    [BASE_LOCATION_ID + 0x55] = { { "@Clock Tower A/Attic Engine Room/Life Max Up" } },
    [BASE_LOCATION_ID + 0x89] = { { "@Clock Tower A/Above Grandfather Ruler/Scale Armor" } },
    [BASE_LOCATION_ID + 0x73] = { { "@Clock Tower A/Skull Painting Room Attic/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x25] = { { "@Clock Tower A/Flea Man Fleapit/Castle Map 3" } },
    [BASE_LOCATION_ID + 0xDE] = { { "@Clock Tower A/Bottom East Shaft White Dragon/Antique Table" } },
    [BASE_LOCATION_ID + 0x0D] = { { "@Clock Tower A/Guardian Grinder/Far-Left (Guardian Glove)" } },
    [BASE_LOCATION_ID + 0x0E] = { { "@Clock Tower A/Guardian Grinder/Mid-Left (Guardian Boots)" } },
    [BASE_LOCATION_ID + 0x0C] = { { "@Clock Tower A/Guardian Grinder/Mid-Right (Guardian Helm)" } },
    [BASE_LOCATION_ID + 0x0B] = { { "@Clock Tower A/Guardian Grinder/Far-Right (Guardian Armor)" } },
    [BASE_LOCATION_ID + 0x29] = { { "@Clock Tower A/Max Slimer's Feathery Friends/Green Stone" } },
    [BASE_LOCATION_ID + 0xDF] = { { "@Clock Tower A/Pinball Zone End/Bottom-Left (Lucky Cat)" } },
    [BASE_LOCATION_ID + 0x1A] = { { "@Clock Tower A/Pinball Zone End/Top (Bolt Book)" } },
    [BASE_LOCATION_ID + 0x4E] = { { "@Clock Tower A/Pinball Zone End/Middle (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x6E] = { { "@Clock Tower A/Pinball Zone End/Bottom Right (Heart Max Up)" } },
    [BASE_LOCATION_ID + 0x16] = { { "@Clock Tower A/Pinball Zone Illusory Crawlspace/Fang of Vlad" } },

    -- Aqueduct of Dragons A
    [BASE_LOCATION_ID + 0x15] = { { "@Aqueduct of Dragons A/Goddess's Illusory Wall/Nail of Vlad" } },
    [BASE_LOCATION_ID + 0xA9] = { { "@Aqueduct of Dragons A/Slimy Pipe Shaft/Hard Gloves" } },
    [BASE_LOCATION_ID + 0x74] = { { "@Aqueduct of Dragons A/Marauding Mermen Territory/Heart Max Up" } },
    [BASE_LOCATION_ID + 0x27] = { { "@Aqueduct of Dragons A/Guillotine Corridor/Blue Stone" } },
    [BASE_LOCATION_ID + 0x57] = { { "@Aqueduct of Dragons A/Behind Giant Merman/Left (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x75] = { { "@Aqueduct of Dragons A/Behind Giant Merman/Right (Heart Max Up)" } },

    -- Castle Top Floor A
    [BASE_LOCATION_ID + 0xC0] = { { "@Castle Top Floor A/Handy Statue Attic - Middle/Left (Elixir)" } },
    [BASE_LOCATION_ID + 0xC1] = { { "@Castle Top Floor A/Handy Statue Attic Stairs/Turkey" } },
    [BASE_LOCATION_ID + 0xC2] = { { "@Castle Top Floor A/Handy Statue Attic - Middle/Middle (Silver Candle)" } },
    [BASE_LOCATION_ID + 0x50] = { { "@Castle Top Floor A/Handy Statue Attic - Right/Life Max Up" } },
    [BASE_LOCATION_ID + 0xC3] = { { "@Castle Top Floor A/Handy Statue Attic Stairs Ledge/Big Mana Prism" } },
    [BASE_LOCATION_ID + 0x51] = { { "@Castle Top Floor A/Lydie's Balcony Tower Top/Left (Life Max Up)" } },
    [BASE_LOCATION_ID + 0x70] = { { "@Castle Top Floor A/Lydie's Balcony Tower Top/Right (Heart Max Up)" } },
    [BASE_LOCATION_ID + 0xC4] = { { "@Castle Top Floor A/Above Minotaur Lv2 Corridor/Castle Drawing" } },
    [BASE_LOCATION_ID + 0xC5] = { { "@Castle Top Floor A/Elevator Room Stairs/Elixir" } },
    [BASE_LOCATION_ID + 0x8E] = { { "@Castle Top Floor A/Corridor Griffin Passage/Silver Armor" } },
    [BASE_LOCATION_ID + 0x2A] = { { "@Castle Top Floor A/Behind Minotaur Lv2/Steel Tip" } },
    [BASE_LOCATION_ID + 0x87] = { { "@Castle Top Floor A/Before Pazuzu Warp Room/Mystic Brooch" } },


	-- Endings (don't work because AP doesn't send ID-less data 😔)
    --["Medium Ending"] = { { "@Castle Treasury A/Ending/Bad" } },
    --["Worst Ending"] = { { "@Castle Treasury B/Ending/Worst" } },
    --["Best Ending"] = { { "@Castle Treasury B/Ending/Best" } },
    --["Furniture Objective"] = { { "@Castle Treasury B/Ending/Retail Employee of the Month" } },
}
