-- Rooms
Tracker:AddLocations("locations/a/rooms/entrance.jsonc")
Tracker:AddLocations("locations/a/rooms/marble_corridor.jsonc")
Tracker:AddLocations("locations/a/rooms/room_of_illusion.jsonc")
Tracker:AddLocations("locations/a/rooms/the_wailing_way.jsonc")
Tracker:AddLocations("locations/a/rooms/shrine_of_the_apostates.jsonc")
Tracker:AddLocations("locations/a/rooms/castle_treasury.jsonc")
Tracker:AddLocations("locations/a/rooms/skeleton_cave.jsonc")
Tracker:AddLocations("locations/a/rooms/luminous_cavern.jsonc")
Tracker:AddLocations("locations/a/rooms/sky_walkway.jsonc")
Tracker:AddLocations("locations/a/rooms/chapel_of_dissonance.jsonc")
Tracker:AddLocations("locations/a/rooms/aqueduct_of_dragons.jsonc")
Tracker:AddLocations("locations/a/rooms/clock_tower.jsonc")
Tracker:AddLocations("locations/a/rooms/castle_top_floor.jsonc")
Tracker:AddLocations("locations/b/rooms/entrance.jsonc")
Tracker:AddLocations("locations/b/rooms/marble_corridor.jsonc")
Tracker:AddLocations("locations/b/rooms/room_of_illusion.jsonc")
Tracker:AddLocations("locations/b/rooms/the_wailing_way.jsonc")
Tracker:AddLocations("locations/b/rooms/shrine_of_the_apostates.jsonc")
Tracker:AddLocations("locations/b/rooms/castle_treasury.jsonc")
Tracker:AddLocations("locations/b/rooms/skeleton_cave.jsonc")
Tracker:AddLocations("locations/b/rooms/luminous_cavern.jsonc")
Tracker:AddLocations("locations/b/rooms/sky_walkway.jsonc")
Tracker:AddLocations("locations/b/rooms/chapel_of_dissonance.jsonc")
Tracker:AddLocations("locations/b/rooms/aqueduct_of_dragons.jsonc")
Tracker:AddLocations("locations/b/rooms/clock_tower.jsonc")
Tracker:AddLocations("locations/b/rooms/castle_top_floor.jsonc")

-- Locations
Tracker:AddLocations("locations/a/entrance.jsonc")
Tracker:AddLocations("locations/a/marble_corridor.jsonc")
Tracker:AddLocations("locations/a/room_of_illusion.jsonc")
Tracker:AddLocations("locations/a/the_wailing_way.jsonc")
Tracker:AddLocations("locations/a/shrine_of_the_apostates.jsonc")
Tracker:AddLocations("locations/a/castle_treasury.jsonc")
Tracker:AddLocations("locations/a/skeleton_cave.jsonc")
Tracker:AddLocations("locations/a/luminous_cavern.jsonc")
Tracker:AddLocations("locations/a/sky_walkway.jsonc")
Tracker:AddLocations("locations/a/chapel_of_dissonance.jsonc")
Tracker:AddLocations("locations/a/aqueduct_of_dragons.jsonc")
Tracker:AddLocations("locations/a/clock_tower.jsonc")
Tracker:AddLocations("locations/a/castle_top_floor.jsonc")
Tracker:AddLocations("locations/b/entrance.jsonc")
Tracker:AddLocations("locations/b/marble_corridor.jsonc")
Tracker:AddLocations("locations/b/room_of_illusion.jsonc")
Tracker:AddLocations("locations/b/the_wailing_way.jsonc")
Tracker:AddLocations("locations/b/shrine_of_the_apostates.jsonc")
Tracker:AddLocations("locations/b/castle_treasury.jsonc")
Tracker:AddLocations("locations/b/skeleton_cave.jsonc")
Tracker:AddLocations("locations/b/luminous_cavern.jsonc")
Tracker:AddLocations("locations/b/sky_walkway.jsonc")
Tracker:AddLocations("locations/b/chapel_of_dissonance.jsonc")
Tracker:AddLocations("locations/b/aqueduct_of_dragons.jsonc")
Tracker:AddLocations("locations/b/clock_tower.jsonc")
Tracker:AddLocations("locations/b/castle_top_floor.jsonc")

Tracker:AddLocations("locations/bosses.jsonc")
Tracker:AddLocations("locations/connecting_portal.jsonc")
Tracker:AddLocations("locations/endings.jsonc")

-- Doors
Tracker:AddLocations("locations/a/area_connection.jsonc")
Tracker:AddLocations("locations/b/area_connection.jsonc")